Add regex matching for whitelist #1
GovTechSG/LicenseFinder pull request #2
Opened 2016-10-03 10:50 UTC by ylhlh

2016-10-04 01:49 UTC, lawliet89 commented on lib/license_finder/decisions.rb
> +    def whitelist_regex_match?(lic)
```ruby
def whitelist_regex_match?(lic)
  @whitelisted.each do |l|
    if lic.name.to_s =~ RegexParser.parse(l.name)
      return true
    end
  end
  false
end
```

2016-10-04 01:49 UTC, lawliet89 commented on lib/license_finder/decisions.rb
> +      match = s.match(/\/(.*)\/(.*)/) or return
Can you explain what you are trying to achieve here?

2016-10-04 02:11 UTC, lawliet89 reviewed
Seems to be within the acceptance criteria. Please add tests.

2016-10-04 02:11 UTC, lawliet89 commented on lib/license_finder/decisions.rb
> +end
Please add a trailing new line.

2016-10-04 02:11 UTC, lawliet89 commented on lib/license_finder/decisions.rb
> +      optmap = {
`optmap` can be a constant.

2016-10-04 02:11 UTC, lawliet89 commented on lib/license_finder/decisions.rb
> +      opts = opt_str.split(//).map { |c| optmap[c] }.reduce { |x, n| x | n }
```ruby
opts = opt_str.each_char.map{ |c| optmap[c] }.reduce { |opt, all_opt| opt | all_opt }
```

2016-10-04 15:24 UTC, ylhlh commented
Thanks for the suggestions. I have updated the code and added a few tests, let me know if there's anything else!

2016-10-04 15:33 UTC, ylhlh commented on lib/license_finder/decisions.rb
> +end
Oops I misunderstood what you meant, please see the latest commit for fix.

2016-10-05 01:46 UTC, lawliet89 requested changes
Good to go except for the regex changes.

Don't worry about the test failures for `Ruby < 2.2.2` for now.  We'll go look into them.

2016-10-05 01:46 UTC, lawliet89 commented on lib/license_finder/decisions.rb
> +      match = s.match(/\/(.*)\/(.*)/) or return
The regex can be improved to `^\/(.+)\/(.*)$`

The changes are:
 - The whole string must be a regex to work. So test strings like `sometfoobar/apache/i` won't work.
 - We don't want to match `//` so I've changed the first capture group to be `(.+)` instead.

Please add tests for both changes.

2016-10-05 10:12 UTC, ylhlh commented
Added the regex change and tests to ensure it works as expected.

2016-10-05 14:05 UTC, lawliet89 approved these changes

2016-10-05 15:01 UTC, lawliet89 commented
Thanks for the work. I am not merging this in yet, while I await some changes from upstream.

Please login to [govBuy](https://buy.gds-gov.tech/) and mark your action as done. We will email you separately for payment details.

2016-10-05 15:52 UTC, ylhlh commented
Ok, thanks so much for the help! :)

2018-04-12 21:12 UTC, closed without merging